on: push
name: Deploy
jobs:
  clean-generate-deploy:
    name: clean-generate-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    - name: Install Hexo
      run: npm install hexo --save
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: cdfmlr@163.com
        NAME: cdfmlr
      with:
        args: deploy
